### PR TITLE
Update UPMissions.txt

### PR DESCRIPTION
**Pull request by Alkallid**
Did I do it right?

### CODE REVIEW

**Comment by LocalGod79** [comment]
you need to update your fork - i released an update today, and it's created some conflicts.

**Comment by Alkallid** [comment]
Oh boy

**Comment by Alkallid** [comment]
It shall be done!

**Comment by Alkallid** [comment]
What am I missing, I only needed to fix missions.txt, right?
Does it have something to do with I don't even know?

**Comment by LocalGod79** [comment]
resolving conflicts like this is pretty difficult in the browser (i don't even know how to do it).

i'm going to see what i can do...

**Comment by LocalGod79** [comment]
wow...okay, that didn't work (i tried to take your file and use the github desktop to compare the changes, and it went all wonky - GitHub at its finest)

how much time did you spend on this?

**Comment by Alkallid** [comment]
4 hours or so.

**Comment by LocalGod79** [comment]
would you like to create another commit with your name/chosen handle and some words in the "Special Thanks" section of the ©&credits.txt?

**Comment by Alkallid** [comment]
Sure? You mean credits and ackowledgements?

**Comment by Alkallid** [comment]
Name would be Allister Xu.

**Comment by LocalGod79** [comment]
done

**Comment by LocalGod79** [comment]
fyi, i am removing some of the little bits of personal flavour that you added as i find them - i feel like they change the overall storytelling style that i was using...

**Comment by LocalGod79** [comment]
got to the deep mission

i'm reverting your commit

**Comment by Alkallid** [comment]
Kay

**Comment by Alkallid** [comment]
That one was especially a joke... I'd have been suprised if yoi left it in.

**Comment by LocalGod79** [comment]
the problem was that the changes were so wholesale, i couldn't see them all - github basically showed me "everything deleted, this in place"...

perhaps try doing pulls two or three missions at a time?

**Comment by Alkallid** [comment]
I'll try next time but I don't think there'll be any more wall-of-texts...

I hope

**Comment by Alkallid** [comment]
Woah this still exists- would you like me to redo all of this, (lenny not included?)

**Comment by LocalGod79** [comment]
if you're willing...

i would say try to do just a mission or two per pull request, so that GitHub can track the changes better, i can better analyze them, and you're not hunched in front of your computer for four hours straight...

**Comment by Alkallid** [comment]
Please, I got arthritis _looong_ ago.

**Pull request merged**
